inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
AllCops:
  Exclude:
      - db/migrate/**/*
      - db/schema.rb
      - config/**/*
      - bin/**/*
      - node_modules/**/*
      - Gemfile
      - Rakefile
      - config.ru
  NewCops: enable

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: To help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false